apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deploy
  labels:
    name: voting-deploy
    app: voting-app-deploy 

spec:
  replicas: 1
  selector:
    matchLabels:
      name: voting-pod
      app: votingapp

  template:
    metadata: 
      name: voting-pod
      labels: 
        name: voting-pod
        app: votingapp

    spec:
      containers:
        - name: votingappcont
          image: kodekloud/examplevotingapp_vote:v1
          ports:
            - containerPort: 80