apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels:
    name: postgres-deploy
    app: voting-app-deploy 

spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: votingapp

  template:
    metadata: 
      name: postgres-pod
      labels: 
        name: postgres-pod
        app: votingapp

    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "posgres"
            - name: POSTGRES_PASSWORD
              value: "posgres"