apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deploy
  labels:
    name: result-deploy
    app: voting-app-deploy 

spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-pod
      app: votingapp

  template:
    metadata: 
      name: result-pod
      labels: 
        name: result-pod
        app: votingapp

    spec:
      containers:
        - name: resultappcont
          image: kodekloud/examplevotingapp_result:v1 
          ports:
            - containerPort: 80