apiVersion: v1
kind: Pod
metadata: 
  name: voting-pod
  labels: 
    name: voting-pod
    app: votingapp

spec:
  containers:
    - name: votingappcont
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80