apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: voting-app-deploy 

spec:
  replicas: 1
  selector:
    matchLabels:
      name: worker-pod
      app: votingapp

  template:
    metadata: 
      name: worker-pod
      labels: 
        name: worker-pod
        app: votingapp

    spec:
      containers:
        - name: worker-app
          image: kodekloud/examplevotingapp_worker:v1